import "bootstrap/dist/css/bootstrap.min.css";
import '@/styles/globals.scss'
import { Inter } from 'next/font/google'
import { TheHeader } from '@/components/TheHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({ children, params: { id } }) {
  return (
    <html lang="en">
      <head>
        {/* <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous" /> */}
        <link
          rel="stylesheet"
          type="text/css"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
      </head>
      <body>
        <TheHeader />
        <main className={inter.className + ' container mt-5'}>
          <div className="main_container">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
