import "bootstrap/dist/css/bootstrap.min.css";
import './globals.scss'
import { Inter } from 'next/font/google'
import { TheHeader } from '@/components/TheHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params: { id } }) {
  return (
    <html lang="en">
      <body>
        <TheHeader />
        <main className={inter.className + ' container'}>
          <div className="main_container">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
