version: '3.7'
services:
  app:
    image: node
    # build: 
    #   context: ./
    #   dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app/next_test
    ports:
      - 9000:9000
    command: npm run dev
