version: '3.7'
services:
  next:
    image: node
    # build: 
    #   context: ./
    #   dockerfile: Dockerfile
    volumes:
      - ./next:/next
    working_dir: /next
    ports:
      - 3000:3000
    command: npm run dev

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - mysql
      - redis
    ports:
      - 4000:4000
    command: bundle exec puma -b 'tcp://0.0.0.0:4000' -C config/puma.rb

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - next_test_mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: next_test
      MYSQL_USER: next_test
      MYSQL_PASSWORD: next_test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  redis:
    image: redis:7.0
    restart: unless-stopped
    volumes:
      - next_test_redis:/data

volumes:
  next_test_mysql:
    driver: local
  next_test_redis:
    driver: local

networks:
  default:
